services:
  - type: web
    name: dinamica-dashboard-financeiro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: SIENGE_USERNAME
        sync: false
      - key: SIENGE_PASSWORD
        sync: false
      - key: SIENGE_INSTANCE
        sync: false
